### ISSUE TITLE
MVPリリースのレビュー依頼

### ISSUE THREAD

**Issue by Yuki11saitou** [Yuki11saitou/LearnLocator#120]
## 各種情報
サービス名：LearnLocator
サービスURL：https://learnlocator.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] レスポンシブ対応
- [x] ユーザー登録機能
- [x] ログイン・ログアウト機能
- [x] 周辺の勉強場所リサーチ(場所検索)
  - [x] Google Geolocation APIで現在地取得し、現在地周辺の勉強場所を取得
  - [x] Google Maps JavaScript APIで地図表示
- [x] 勉強場所詳細
  - [x] Google Places APIで「勉強場所の詳細情報」の取得・表示（あらかじめDBに保存）　
    - [x] 勉強場所の　名前/住所/営業時間/電話番号/公式HPリンク　
  - [x] 「ここへ行く」ボタン押下でGoogleMapに遷移し、ナビゲーションまたは乗換案内ページを表示

### 開発途中でMVPリリース時点で作らなくなった機能

- [ ] 勉強場所一覧(一覧検索)
  - [ ] 検索機能（　カテゴリー[図書館/自習室/コワーキングスペース]・地域・施設名　）
- [ ] 勉強場所詳細
  - [ ] Google Maps JavaScript APIで地図表示（⚠️これは本リリースでも作らない）
  - [ ] ブックマーク登録機能
  - [ ] 口コミ投稿機能（編集・削除機能は投稿主のみ許可）
  - [ ] 口コミに対する「いいね」機能
- [ ] マイページ
  - [ ] 自身の投稿した口コミ一覧
  - [ ] 「いいね」した口コミ一覧
- [ ] ブックマーク登録した勉強場所の一覧

### 「ユーザー登録」および「ログイン・ログアウト」機能について
- 今回、「ユーザー登録」および「ログイン・ログアウト」機能を実装しましたが、ヘッダーのハンバーガーメニューの表示以外、変わりません。
- また、表示だけでなく使用できる機能も変わりません。
- ハンバーガーメニューの上2つの項目が、ログインとログアウトで切り替わります。
- 今回、私のアプリは「ユーザー登録」や「ログイン・ログアウト」がメイン機能と関与しないため、このような状態になっています。

＜ログイン前＞
[![Image from Gyazo](https://i.gyazo.com/68e6b13add955b57b7f40c2c19363af9.png)](https://gyazo.com/68e6b13add955b57b7f40c2c19363af9)

＜ログイン後＞
[![Image from Gyazo](https://i.gyazo.com/606943425e3adf3526efa3cce13499d7.png)](https://gyazo.com/606943425e3adf3526efa3cce13499d7)

### 登録した「自習室」「コワーキングスペース」のデータについて
- 今回は、”埼玉県内”の施設のみDBに保存しています。
- 今後エリア拡大予定ですが、技術面談でも相談させていただき、これでレビューを出させていただきます。

＜マップのマーカーの様子（埼玉県のみ対応）＞
[![Image from Gyazo](https://i.gyazo.com/0aba4176f1bbaed37b19e24ad9c7f604.png)](https://gyazo.com/0aba4176f1bbaed37b19e24ad9c7f604)

**Comment by TakenakaEri** [comment]
確認しました！

MVPの内容が実装できているので、LGTMです！！

この後の本リリースの内容もしっかりと自分の中で計画を立てて考えてらっしゃるので、この後も本リリースまで頑張って進めてくださいね！！
