### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Yuki11saitou** [Yuki11saitou/LearnLocator#78]
## 概要
"issueベースの開発"レビュー依頼になります。
ご確認のほどよろしくお願いいたします。

### MVPリリース
- [x] ユーザー登録機能
- [x] ログイン・ログアウト機能
- 周辺の勉強場所リサーチ(場所検索)
  - [x] 現在地取得、現在地周辺の勉強場所を取得
  - [x] 地図表示
- 勉強場所一覧(一覧検索)
  - [x] 検索機能
- 勉強場所詳細
  - [x] 「勉強場所の詳細情報」の取得・表示
  - [x] 勉強場所の地図表示
  - [x] 「ここへ行く」でGoogleMapに遷移し、ナビゲーション表示
  - [x] ブックマーク登録機能
  - [x] 口コミ投稿・編集・削除の機能（編集・削除機能は投稿主のみ許可）
  - [x] 口コミに対する「いいね」機能
- マイページ
  - [x] 自身の投稿した口コミ一覧表示
  - [x] 自身の「いいね」した口コミ一覧表示
- [x] ブックマーク登録した勉強場所の一覧表示

### 必要なページ(MVP)
- [x] topページ
- ユーザー登録系
  - [x] Login画面
  - [x] Login画面【モーダル】
  - [x] 新規登録画面 
- マイページ系
  - [x] マイページ画面(いいね一覧タブver)
  - [x] マイページ画面(投稿一覧タブver)
  - [x] マイページ編集画面
- 場所検索系
  - [x] 勉強場所一覧画面(地図のみ表示ver)
  - [x] 勉強場所一覧画面(詳細モーダル表示ver)
- 一覧検索系
  - [x] 一覧検索画面
- 診断系
  - [x] 診断の質問画面
  - [x] 診断の結果画面
- ブックマーク系
  - [x] ブックマーク一覧画面
- 施設情報系
  - [x] 施設詳細画面(施設情報タブver)
  - [x] 施設詳細画面(口コミ一覧タブver)
  - [x] 施設詳細画面(口コミ新規投稿用モーダル表示ver)

## 補足
- 画面遷移図リンク(Figma)：  
https://www.figma.com/design/jEObdmmCqTXRWpQH72SY9A/LearnLocator_%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3?node-id=0-1&t=v0b8MOyi8cjFOjZg-1

- プロジェクトのURL：  
https://github.com/users/Yuki11saitou/projects/1

- 勉強場所データについて：
MVP時点では、ひとまず「埼玉県」のデータ取得のみの予定でissueを切っています。
  - 対応issue : #73 #74 #75 #76

**Comment by kenchasonakai** [comment]
LGTMです！
